app:
  clients:
    - id: account-service
      secret: ${ACCOUNT_SERVICE_PASSWORD}
      url: http://${ACCOUNT_SERVICE_IP}:${ACCOUNT_SERVICE_PORT:80}

    - id: chat-service
      secret: ${CHAT_SERVICE_PASSWORD}
      url: http://${CHAT_SERVICE_IP}:${ACCOUNT_SERVICE_PORT:80}
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_IP}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}

  jpa.hibernate.ddl-auto: create

  security:
    oauth2:
      authorizationserver:
        issuer: http://${IP}:80

management:
  endpoint.health.probes.enabled: true
  health:
    livenessState.enabled: true
    readinessState.enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_IP}:${REGISTRY_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true

server.port: 80
