apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.auth.service.name }}-deployment
  labels:
    app: {{ .Values.global.auth.service.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.auth.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.auth.service.name }}
    spec:
      containers:
        - name: {{ .Values.global.auth.service.name }}-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            # itself ip
            - name: IP
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.registry.name }}-configmap
                  key: auth_service_ip
            # registry service
            - name: REGISTRY_IP
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.registry.name }}-configmap
                  key: registry_service_ip

            # account client
            - name: ACCOUNT_SERVICE_IP
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.registry.name }}-configmap
                  key: account_service_ip

            - name: ACCOUNT_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.auth.service.name }}-secret
                  key: account_client_password

            # chat client
            - name: CHAT_SERVICE_IP
              value: {{ .Values.global.registry.namee }}-service

            - name: CHAT_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.auth.service.name }}-secret
                  key: chat_client_password

            # database
            - name: POSTGRES_IP
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.auth.service.name }}-configmap
                  key: postgres_service_ip

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.auth.postgres.name }}-secret
                  key: db_password

            # csrf
            - name: CSRF_ENABLED
              value: {{ .Values.global.csrf.enabled }}