apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  labels:
    app: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
        - name: chat-app
          image: patryklikus/chatwave-chatservice:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            # REGISTRY SERVICE
            - name: REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: registry_url

            # PASSWORD TO AUTH-SERVICE
            - name: AUTH_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: chat_password

            # DATABASE
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: chat_db_url

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: chat-postgres-configmap
                  key: db_name

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: chat-postgres-secret
                  key: username

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-postgres-secret
                  key: password
                  
            # OTHERS
            - name: CSRF_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: csrf_enabled
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
