apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: auth-app
          image: patryklikus/chatwave-authservice:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            # REGISTRY SERVICE
            - name: REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: registry_url

            # ACCOUNT CLIENT
            - name: ACCOUNT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: account_service_url

            - name: ACCOUNT_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: account_password

            # CHAT CLIENT
            - name: CHAT_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: chat_password

            - name: CHAT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: chat_service_url
                  
            # DATABASE
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: auth_db_url

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: auth-postgres-configmap
                  key: db_name

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: auth-postgres-secret
                  key: username

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-postgres-secret
                  key: password
                  
            # OTHERS
            - name: CSRF_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: csrf_enabled
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
