spring:
  datasource:
    url: jdbc:postgresql://account-postgres:5432/chatwave
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8081
      client:
        provider:
          auth-service:
            issuer-uri: http://auth-service:8081
        registration:
          auth-service:
            client-id: account-client
            client-secret: secret
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            redirect-uri:  "{baseUrl}/login/oauth2/code/spring"
            scope:
              - openid
              - server

  cloud:
    openfeign:
      oauth2:
        enabled: true

server:
  port: 8082
