spring:
  datasource:
    url: jdbc:postgresql://chat-postgres:5432/chatwave
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8081
          jwk-set-uri: http://auth-service:8081/oauth2/jwks
      client:
        provider:
          microservices:
            issuer-uri: http://auth-service:8081
            jwk-set-uri: http://auth-service:8081/oauth2/jwks
        registration:
          microservices:
            client-id: chat-service
            client-secret: secret
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/spring"
            scope:
              - openid
              - server

  cloud:
    openfeign:
      oauth2:
        clientRegistrationId: microservices
        enabled: true

server:
  port: 8083
