app.csrf.enabled: ${CSRF_ENABLED:true}

spring:
  application:
    name: chat-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5432/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        provider:
          microservices:
            issuer-uri: http://${AUTH_SERVICE_URL}:80
            jwk-set-uri: http://${AUTH_SERVICE_URL}:80/oauth2/jwks
        registration:
          microservices:
            client-id: chat-service
            client-secret: ${AUTH_SERVICE_PASSWORD}
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/spring"
            scope:
              - openid
              - server

  cloud:
    openfeign:
      oauth2:
        clientRegistrationId: microservices
        enabled: true

server.port: 80
